export enum Service {
  OIL_CHANGE = 'OIL_CHANGE',

  TIRE_ROTATION = 'TIRE_ROTATION',

  BRAKE_SERVICE = 'BRAKE_SERVICE',

  PPF = 'PPF',

  TINT = 'TINT',

  DETAILING = 'DETAILING',

  AIR_FILTER = 'AIR_FILTER',

  CERAMIC_COATING = 'CERAMIC_COATING',
}
